- name: nginx install and run 
  hosts: nginx
  become: yes  # it takes sudo access
  serial: 2
  tasks:
   - name: install nginx 
     ansible.builtin.package:  # ansible is heterogenous module that can work for all distros
      name: nginx 
      state: present

   - name: run nginx 
     ansible.builtin.service:  # service module is used to manage services
      name: nginx
      state: started
      enabled: yes